"""empty message

Revision ID: 3f4fa0bacb8e
Revises: 7bfcd17ad81c
Create Date: 2016-04-07 09:33:04.242000

"""

# revision identifiers, used by Alembic.
revision = '3f4fa0bacb8e'
down_revision = '7bfcd17ad81c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filename', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'filename')
    ### end Alembic commands ###
