"""empty message

Revision ID: 4bb7cfa6dc0c
Revises: 3f4fa0bacb8e
Create Date: 2016-04-21 10:15:00.671000

"""

# revision identifiers, used by Alembic.
revision = '4bb7cfa6dc0c'
down_revision = '3f4fa0bacb8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_column('users', 'filename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_url')
    ### end Alembic commands ###
